Repository innovationacademy-kr/42dashboard, pull requests merged in 2022-08, with the labels that each got.

#350 feat(client/board): presetlist에 아이템 유무에 따른 보드 렌더링 처리
  packages/client/src/dashboard/application/services/usePreset.tsx
Labels: front-end

#361 feat(board): feat: add data refresh button
  packages/client/src/dashboard/infrastructure/http/axios/axios.custom.ts
  packages/client/src/dashboard/presentation/components/ModeDial/ModeDial.tsx
Labels: front-end

#363 fix(client): can edit dataset name
  packages/client/src/dashboard/presentation/components/Modal/Dataset.tsx
  packages/client/src/dashboard/presentation/components/Modal/Modal.tsx
Labels: front-end

#373 feat(client/Table): tableContentSticker 컴포넌트 추가. 해당 컴포넌트의 기본 값으로 모든 컬…
  docker-compose.yml
  packages/client/.storybook/preview.js
  packages/client/src/dashboard/application/utils/DEFAULT_TABLE_PROPS.ts
  packages/client/src/dashboard/application/utils/camelize.ts
  packages/client/src/dashboard/application/utils/tableQueryParse.js
  packages/client/src/dashboard/presentation/components/Login/Login.tsx
  packages/client/src/dashboard/presentation/components/Modal/Modal.tsx
  packages/client/src/dashboard/presentation/components/Modal/makeStickerData.ts
  packages/client/src/dashboard/presentation/components/Sticker/StickerContent.type.ts
  packages/client/src/dashboard/presentation/components/Sticker/StickerContentFactory.tsx
  packages/client/src/dashboard/presentation/components/Table/Table.tsx
  packages/client/src/dashboard/presentation/pages/DashBoardPage.tsx
  packages/client/src/index.tsx
Labels: front-end

#385 feat(server/modify): feat: add modify exception
  packages/server/src/schema.gql
  packages/server/src/spread/msg/errorMsg.msg.ts
  packages/server/src/spread/spread.service.ts
  packages/server/src/updater/name_types/updater.name.ts
  packages/server/src/updater/updater.service.ts
  packages/server/src/user_job/entity/user_job.entity.ts
Labels: back-end

#407 fix(client/modal): filter 설정하는 save 버튼 수정
  packages/client/src/dashboard/presentation/components/Modal/QueryFilterAttribute.tsx
Labels: front-end

#410 fix(client): error if entityName & column is empty
  packages/client/src/dashboard/infrastructure/http/graphql/createQuery.ts
  packages/client/src/dashboard/presentation/components/Dialog/RequestButton.tsx
  packages/client/src/dashboard/presentation/components/Dialog/SaveButton.tsx
  packages/client/src/dashboard/presentation/components/Modal/Dataset.tsx
  packages/client/src/dashboard/presentation/components/Modal/QueryFilterAttribute.tsx
  packages/client/src/dashboard/presentation/components/Modal/StickerStepper.tsx
  packages/client/src/dashboard/presentation/components/Modal/filterAttributes/FilterAttribute.tsx
  packages/client/src/dashboard/presentation/components/Modal/filterAttributes/ValueAttribute.tsx
  packages/client/src/dashboard/presentation/components/Modal/filterAttributes/menuItems/returnColumns.tsx
  packages/client/src/dashboard/presentation/components/Modal/filterAttributes/menuItems/returnValues.tsx
  packages/client/src/dashboard/presentation/components/SideBar/PresetListItem.tsx
  packages/client/src/dashboard/presentation/components/Sticker/Filter.type.ts
Labels: bug, front-end

#422 feat(server/delete modify page): feat: delete function for modify page
  packages/server/src/common/EntityColumn.ts
  packages/server/src/schema.gql
  packages/server/src/spread/spread.service.ts
  packages/server/src/updater/updater.service.ts
  packages/server/src/user_information/argstype/updateSheet.argstype.ts
Labels: back-end

#427 fix(client): manually trigger window resize event
  packages/client/src/dashboard/application/services/useBoard.tsx
Labels: front-end

#435 feat(client): apply datasetnaming to pie and bar chart
  packages/client/src/dashboard/presentation/components/Board/Section.tsx
  packages/client/src/dashboard/presentation/components/Charts/BarChart.tsx
  packages/client/src/dashboard/presentation/components/Charts/PieChart.tsx
  packages/server/package.json
Labels: front-end

#450 feat(server/spread): feat: making error checker to use better
  packages/server/src/updater/updater.service.ts
Labels: back-end

#467 fix(client): rename preset, refresh not occur random list
  packages/client/src/dashboard/application/services/useBoard.tsx
  packages/client/src/dashboard/application/services/usePreset.tsx
  packages/client/src/dashboard/infrastructure/preset.repository.ts
  packages/client/src/dashboard/infrastructure/store/preset.store.ts
  packages/client/src/dashboard/presentation/components/Footer/Footer.tsx
  packages/client/src/dashboard/presentation/components/SideBar/PresetListItem.tsx
  packages/client/src/dashboard/presentation/components/SideBar/SideBar.tsx
  packages/client/src/dashboard/presentation/pages/DashBoardPage.tsx
Labels: front-end

#475 feat(server/updater): 학습데이터 기준 일자 변경
  packages/server/src/spread/spread.service.ts
  packages/server/src/updater/name_types/updater.name.ts
  packages/server/src/updater/updater.service.ts
Labels: back-end

#487 fix(server/updater): computation 산정 계산 값 처리
  packages/server/src/api/api.service.ts
  packages/server/src/app.module.ts
  packages/server/src/spread/spread.service.ts
  packages/server/src/type.ts/entityType.ts
  packages/server/src/updater/updater.service.ts
Labels: back-end

#489 fix(client): edit selected randomly
  packages/client/src/dashboard/application/services/usePreset.tsx
  packages/client/src/dashboard/domain/preset/preset.repository.interface.ts
  packages/client/src/dashboard/domain/preset/preset.service.ts
  packages/client/src/dashboard/domain/presetList/presetList.service.ts
  packages/client/src/dashboard/infrastructure/http/graphql/createQuery.ts
  packages/client/src/dashboard/infrastructure/http/graphql/createValueQuery.ts
  packages/client/src/dashboard/infrastructure/preset.repository.ts
  packages/client/src/dashboard/infrastructure/presetList.repository.ts
  packages/client/src/dashboard/infrastructure/store/preset.store.ts
  packages/client/src/dashboard/presentation/components/Footer/Footer.tsx
  packages/client/src/dashboard/presentation/components/SideBar/PresetListItem.tsx
  packages/client/src/dashboard/presentation/components/SideBar/SideBar.tsx
  packages/server/src/spread/spread.service.ts
Labels: front-end

#493 chore(client): 브라우저 탭 favicon, title 적용
  packages/client/public/favicon.ico
  packages/client/public/index.html
Labels: front-end
