Repository innovationacademy-kr/42dashboard, pull requests merged in 2022-06, with the labels that each got.

#51 ci(root) : 리포지터리에 풀리퀘스트 탬플릿 적용
  .github/PULL_REQUEST_TEMPLATE/bug_fix.md
  .github/PULL_REQUEST_TEMPLATE/feature.md
Labels: documentation, design, common

#97 feat(board section): add: structure board section
  packages/client/package.json
  packages/client/src/App.tsx
  packages/client/src/dashboard/presentation/components/Board/Board.tsx
  packages/client/src/dashboard/presentation/components/Board/index.tsx
  packages/client/src/dashboard/presentation/components/Board/styles.css
  packages/client/src/dashboard/presentation/components/Board/styles2.css
  packages/client/src/dashboard/presentation/components/Section/Section.tsx
  packages/client/src/dashboard/presentation/components/Section/styles.css
  packages/client/src/dashboard/presentation/components/Section/styles2.css
  packages/client/src/index.tsx
Labels: enhancement, good first issue, front-end

#100 fix(component): fixed: cannot re-render sticker when section resized
  packages/client/src/dashboard/presentation/components/Board/Board.tsx
  packages/client/src/dashboard/presentation/components/Board/Section.tsx
  packages/client/src/dashboard/presentation/components/Section/styles.css
  packages/client/src/dashboard/presentation/components/Section/styles2.css
Labels: bug, front-end

#106 feat(client,charts): chartjs 모듈 추가, Pie Chart 추가
  packages/client/package.json
  packages/client/src/dashboard/presentation/components/Charts/ChartData.ts
  packages/client/src/dashboard/presentation/components/Charts/PieChart.tsx
Labels: enhancement, front-end

#112 add: github action: lint check & front build
  .github/workflows/yarn-grunt.yaml
Labels: common
