Repository innovationacademy-kr/42dashboard, pull requests merged in 2022-07, with the labels that each got.

#114 feat(client,Charts): PieChart에 대한 스토리 작성
  packages/client/src/dashboard/presentation/components/Charts/PieChart.stories.tsx
  packages/client/src/dashboard/presentation/components/Charts/PieChart.tsx
Labels: front-end

#120 fix(client/charts): fix build error
  packages/client/src/dashboard/presentation/components/Charts/PieChart.tsx
Labels: front-end

#130 fix(server): fixed: progress entity type changed
  packages/server/src/app.module.ts
  packages/server/src/schema.gql
  packages/server/src/user_information/user_information.service.ts
  packages/server/src/user_status/entity/user_status.entity.ts
Labels: bug, back-end

#135 feat(client/dashboardpage): add modedial component
  packages/client/src/dashboard/presentation/components/ModeDial/ModeDial.tsx
  packages/client/src/dashboard/presentation/pages/DashBoardPage.tsx
Labels: enhancement, front-end

#142 style(userAccessCardInformationArgs): style: change column name
  packages/server/src/updater/name_types/updater.name.ts
  packages/server/src/user_information/argstype/userAccessCardInformation.ts
  packages/server/src/user_information/entity/user_access_card_information.entity.ts
  packages/server/src/user_information/entity/user_information.entity.ts
Labels: design, back-end

#147 feat(server): postgresql docker
  .DS_Store
  packages/.DS_Store
  packages/server/docker-compose.yml
  packages/server/nestjs.dockerfile
  packages/server/src/schema.gql
Labels: back-end

#146 feat(updater.resolver): updater의 graphQL요청방식 추가
  packages/server/src/app.module.ts
  packages/server/src/schema.gql
  packages/server/src/updater/updater.resolver.ts
Labels: enhancement, back-end

#165 feat(server): api 파싱하여 db에 저장
  packages/server/src/api/api.controller.ts
  packages/server/src/api/api.module.ts
  packages/server/src/api/api.service.ts
  packages/server/src/api/dto/create-api.dto.ts
  packages/server/src/api/entity/api.entity.ts
  packages/server/src/schema.gql
  packages/server/src/updater/name_types/updater.name.ts
  packages/server/src/updater/updater.module.ts
  packages/server/src/updater/updater.service.ts
  packages/server/src/user_information/user_information.module.ts
  packages/server/src/user_information/user_information.service.spec.ts
  packages/server/src/user_information/user_information.service.ts
  packages/server/src/user_status/entity/user_status.entity.ts
Labels: enhancement, back-end

#177 feat(server): 관리자를 위한 graphql api 추가
  packages/server/src/auth/auth.module.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/entity/bocal.entity.ts
  packages/server/src/auth/jwt.strategy.ts
  packages/server/src/schema.gql
  packages/server/src/user_information/argstype/cudDto.argstype.ts
  packages/server/src/user_information/argstype/filter.argstype.ts
  packages/server/src/user_information/argstype/joinedTable.ts
  packages/server/src/user_information/entity/user_access_card_information.entity.ts
  packages/server/src/user_information/entity/user_information.entity.ts
  packages/server/src/user_information/entity/user_other_information.entity.ts
  packages/server/src/user_information/entity/user_personal_information.entity.ts
  packages/server/src/user_information/filter.ts
  packages/server/src/user_information/user_information.controller.ts
  packages/server/src/user_information/user_information.module.ts
  packages/server/src/user_information/user_information.resolver.ts
  packages/server/src/user_information/user_information.service.ts
  packages/server/src/user_job/entity/user_job.entity.ts
  packages/server/src/user_payment/entity/user_computation_fund.entity.ts
  packages/server/src/user_payment/entity/user_education_fund_state.entity.ts
  packages/server/src/user_payment/entity/user_payment.entity.ts
  packages/server/src/user_status/entity/user_status.entity.ts
Labels: enhancement, back-end

#209 fix(server/updater): fixed: fix entity relation
  packages/server/src/user_information/entity/user_access_card_information.entity.ts
  packages/server/src/user_information/entity/user_information.entity.ts
  packages/server/src/user_information/entity/user_personal_information.entity.ts
Labels: bug, back-end

#213 fix(server/spread): fixed: creaForeignKeyConstraints to be true
  packages/server/src/spread/spread.service.ts
  packages/server/src/user_information/entity/user_access_card_information.entity.ts
  packages/server/src/user_information/entity/user_other_information.entity.ts
  packages/server/src/user_information/entity/user_personal_information.entity.ts
  packages/server/src/user_job/entity/user_job.entity.ts
  packages/server/src/user_payment/entity/user_computation_fund.entity.ts
  packages/server/src/user_payment/entity/user_education_fund_state.entity.ts
  packages/server/src/user_status/entity/user_status.entity.ts
Labels: bug, back-end

#239 feat(sever): feat: renewal according to form change
  packages/server/src/api/api.service.ts
  packages/server/src/schema.gql
  packages/server/src/spread/spread.service.ts
  packages/server/src/updater/name_types/updater.name.ts
  packages/server/src/updater/updater.module.ts
  packages/server/src/updater/updater.service.ts
  packages/server/src/user_information/argstype/joinedTable.ts
  packages/server/src/user_information/entity/user_access_card_information.entity.ts
  packages/server/src/user_information/entity/user_information.entity.ts
  packages/server/src/user_information/entity/user_other_information.entity.ts
  packages/server/src/user_information/entity/user_personal_information.entity.ts
  packages/server/src/user_information/user_information.service.ts
  packages/server/src/user_job/entity/user_job.entity.ts
  packages/server/src/user_job/user_job.module.ts
  packages/server/src/user_job/user_job.resolver.ts
  packages/server/src/user_job/user_job.service.ts
  packages/server/src/user_payment/entity/user_computation_fund.entity.ts
  packages/server/src/user_payment/entity/user_education_fund_state.entity.ts
  packages/server/src/user_payment/entity/user_payment.entity.ts
  packages/server/src/user_payment/user_payment.module.ts
  packages/server/src/user_payment/user_payment.resolver.ts
  packages/server/src/user_payment/user_payment.service.ts
  packages/server/src/user_status/entity/user_status.entity.ts
  packages/server/src/user_status/user_status.module.ts
  packages/server/src/user_status/user_status.resolver.ts
  packages/server/src/user_status/user_status.service.ts
Labels: enhancement, back-end

#255 fix(server): fixed: conflict error
  packages/server/src/schema.gql
  packages/server/src/updater/name_types/updater.name.ts
  packages/server/src/user_information/entity/user_information.entity.ts
  packages/server/src/user_information/user_information.service.ts
  packages/server/src/user_job/entity/user_job.entity.ts
Labels: back-end

#267 Hotfix/label filter
  packages/client/src/dashboard/presentation/components/Modal/LabelFilter.tsx
Labels: front-end

#269 feat(client/preset): preset 기능 구현
  docker-compose.yml
  packages/client/src/dashboard/application/services/useBoard.tsx
  packages/client/src/dashboard/application/services/useBoardLayout.tsx
  packages/client/src/dashboard/application/services/usePreset.tsx
  packages/client/src/dashboard/application/services/usePresetList.tsx
  packages/client/src/dashboard/application/services/useSectionLayout.tsx
  packages/client/src/dashboard/domain/preset/preset.repository.interface.ts
  packages/client/src/dashboard/domain/preset/preset.service.ts
  packages/client/src/dashboard/domain/preset/preset.type.ts
  packages/client/src/dashboard/domain/presetList/presetList.repository.interface.ts
  packages/client/src/dashboard/domain/presetList/presetList.service.ts
  packages/client/src/dashboard/domain/presetList/presetList.type.ts
  packages/client/src/dashboard/infrastructure/http/preset.graphql.ts
  packages/client/src/dashboard/infrastructure/preset.repository.ts
  packages/client/src/dashboard/infrastructure/presetList.repository.ts
  packages/client/src/dashboard/infrastructure/store/presetList.store.ts
  packages/client/src/dashboard/infrastructure/store/zustand/dashboard.store.zustand.ts
  packages/client/src/dashboard/presentation/components/Board/Board.tsx
  packages/client/src/dashboard/presentation/components/SideBar/SideBar.tsx
  packages/client/src/dashboard/presentation/components/SideBar/SideBarListItem.tsx
Labels: enhancement, front-end

#271 feat(component/modal): value 받아오는 api 사용하여 value filter 구현
  packages/client/src/dashboard/infrastructure/http/graphql/createValueQuery.ts
  packages/client/src/dashboard/presentation/components/Modal/LabelFilter.tsx
  packages/client/src/dashboard/presentation/components/Modal/useValueDataset.tsx
  packages/client/src/index.tsx
  packages/common/src/EntityColumn.ts
Labels: front-end

#305 style(client): 로고 이미지 추가 및 Logo 컴포넌트 적용
  packages/client/public/favicon.ico
  packages/client/public/logo192.png
  packages/client/public/logo512.png
  packages/client/src/assets/images/logo.png
  packages/client/src/assets/images/logo.svg
  packages/client/src/dashboard/presentation/components/Logo/logo.tsx
  packages/client/src/dashboard/presentation/pages/DashBoardPage.tsx
  packages/client/src/logo.svg
Labels: design, front-end

#319 fix(client): save layout change when window resize event occur
  packages/client/src/dashboard/presentation/components/Board/Board.tsx
Labels: front-end

#325 [좀급함] labelFilter 입력부분과 dataset 입력부분의 공통적인 부분을 추렸습니다.
  packages/client/src/dashboard/presentation/components/Modal/Dataset.tsx
  packages/client/src/dashboard/presentation/components/Modal/InputDatasets.tsx
  packages/client/src/dashboard/presentation/components/Modal/InputLabels.tsx
  packages/client/src/dashboard/presentation/components/Modal/LabelFilter.tsx
  packages/client/src/dashboard/presentation/components/Modal/Modal.tsx
  packages/client/src/dashboard/presentation/components/Modal/QueryFilterAttribute.tsx
  packages/client/src/dashboard/presentation/components/Modal/SelectedFilter.tsx
  packages/client/src/dashboard/presentation/components/Modal/StickerStepper.tsx
Labels: front-end
